load("@roo_testing//roo_testing/emulation:arduino.bzl", "roo_arduino_example")

roo_arduino_example(
    name = "start_stop",
    sketch = "start_stop.ino",
    visibility = ["//visibility:public"],
    deps = ["//:roo_scheduler"],
)
