name: CI

on:
  push: {}

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Mount bazel cache
      uses: actions/cache@v3
      with:
        path: "/home/runner/.cache/bazel"
        key: bazel

    - name: Install bazelisk
      run: |
        curl -LO "https://github.com/bazelbuild/bazelisk/releases/download/v1.1.0/bazelisk-linux-amd64"
        mkdir -p "${GITHUB_WORKSPACE}/bin/"
        mv bazelisk-linux-amd64 "${GITHUB_WORKSPACE}/bin/bazel"
        chmod +x "${GITHUB_WORKSPACE}/bin/bazel"

    - name: Install dependencies
      run: |
        mkdir .testing/lib
        (cd .testing/lib;
         curl -LO "https://github.com/dejwk/roo_backport/archive/refs/tags/1.0.1.zip";
         unzip 1.0.1.zip;
         mv roo_backport-1.0.1 roo_backport)

    - name: Build
      run: |
        (cd .testing; cp -Rf ../src .; ${GITHUB_WORKSPACE}/bin/bazel build //...)

    - name: Test
      run: |
        (cd .testing; ${GITHUB_WORKSPACE}/bin/bazel test //...)
